# Generated by Django 2.0 on 2019-02-21 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Category coming soon', max_length=100)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ebag.Category')),
            ],
        ),
    ]
