# Generated by Django 2.0 on 2019-02-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebag', '0003_auto_20190221_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.IntegerField(default=1),
        ),
    ]
