# Generated by Django 2.0 on 2019-02-21 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebag', '0005_auto_20190221_1646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
