# Generated by Django 2.0 on 2019-02-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebag', '0009_auto_20190221_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.IntegerField(default=0, verbose_name='self.level+1'),
        ),
    ]
