# Generated by Django 2.0 on 2019-02-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebag', '0010_category_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.IntegerField(default=0, verbose_name='f{self.level+1}'),
        ),
    ]
