# Generated by Django 2.0 on 2019-02-21 21:02

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ebag', '0013_auto_20190221_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='lft',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='rght',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=None),
        ),
        migrations.AddField(
            model_name='category',
            name='tree_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ebag.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent_category', 'slug')},
        ),
    ]
