# Generated by Django 2.0 on 2019-02-21 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebag', '0014_auto_20190221_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_category',
            new_name='parent',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent', 'slug')},
        ),
    ]
