# Generated by Django 2.0 on 2019-02-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebag', '0016_auto_20190221_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='New category', max_length=100),
        ),
    ]
