# Generated by Django 2.0 on 2019-02-22 11:50

from django.db import migrations, models
import ebag.models


class Migration(migrations.Migration):

    dependencies = [
        ('ebag', '0018_auto_20190221_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=ebag.models.Product.save_file_with_id_name),
        ),
    ]
