# Generated by Django 2.0 on 2019-02-25 14:00

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ebag', '0020_auto_20190223_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='ebag.Category'),
            preserve_default=False,
        ),
    ]
